apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: hybrid-app
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: DOCKER_REGISTRY/hybrid-python-app:latest
          ports:
            - containerPort: 5000
          env:
            - name: APP_ENV
              value: "eks-production"
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: python-app
  namespace: hybrid-app
spec:
  selector:
    app: python-app
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
