server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /java/ {
        proxy_pass http://java-app:8080/;
        proxy_set_header Host $host;
    }

    location /python/ {
        proxy_pass http://python-app:5000/;
        proxy_set_header Host $host;
    }
}
